PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?Name (xsd:integer(?age) AS ?Age)
WHERE {
  ?person rdf:type foaf:Person ;
          foaf:name ?Name ;
          foaf:age ?age .
  FILTER (xsd:integer(?age) > 10)
}
ORDER BY DESC(?Age)
