PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX fam: <http://www.ifi.uio.no/IN3060/family#>
PREFIX sim: <http://www.ifi.uio.no/IN3060/simpsons#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


CONSTRUCT {
  sim:Homer a foaf:Person ;
            foaf:name "Homer Simpson" ;
            foaf:knows sim:Marge .
  sim:Marge a foaf:Person ;
            foaf:name "Marge Simpson" .
}
WHERE {
  sim:Homer fam:hasSpouse sim:Marge .
}